import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const appSource = await readFile(new URL('../src/App.tsx', import.meta.url), 'utf8');
const sidebarSource = await readFile(new URL('../src/features/admin/AdminSidebar.tsx', import.meta.url), 'utf8');
const listPageSource = await readFile(new URL('../src/pages/admin/AdminErrorLogsPage.tsx', import.meta.url), 'utf8');
const detailPageSource = await readFile(new URL('../src/pages/admin/AdminErrorLogDetailPage.tsx', import.meta.url), 'utf8');
const shellSource = await readFile(new URL('../src/components/layout/AdminShell.tsx', import.meta.url), 'utf8');

assert.match(appSource, /AdminErrorLogsPage/);
assert.match(appSource, /path="error-logs"/);
assert.match(appSource, /AdminErrorLogDetailPage/);
assert.match(appSource, /path="error-logs\/:id"/);
assert.match(sidebarSource, /\/admin\/error-logs/);
assert.match(sidebarSource, /TriangleAlert|Bug|CircleAlert/);
assert.match(shellSource, /\/admin\/error-logs/);
assert.match(listPageSource, /getErrorLogs/);
assert.match(listPageSource, /keyword/);
assert.match(listPageSource, /status/);
assert.match(listPageSource, /method/);
assert.match(listPageSource, /from/);
assert.match(listPageSource, /to/);
assert.match(listPageSource, /type="date"/);
assert.match(listPageSource, /Link/);
assert.match(detailPageSource, /getErrorLogDetail/);
assert.match(detailPageSource, /stackTrace/);
assert.match(detailPageSource, /실제 에러 로그/);
assert.match(detailPageSource, /navigator\.clipboard\.writeText/);
assert.match(detailPageSource, /코드 복사|로그 복사/);
assert.match(detailPageSource, /Copy/);
assert.match(detailPageSource, /Check/);
assert.match(detailPageSource, /document\.execCommand\('copy'\)/);
assert.match(detailPageSource, /useFeedback/);
assert.match(detailPageSource, /에러 로그 복사 완료/);
assert.match(detailPageSource, /에러 로그 복사 실패/);
assert.match(detailPageSource, /복사됨/);
assert.match(detailPageSource, /복사 실패/);
